name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3    # Paso 1: clonar el código:contentReference[oaicite:2]{index=2}
      - name: Setup Python
        uses: actions/setup-python@v5  # Paso 2: instalar Python
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest          # Instalar pytest:contentReference[oaicite:3]{index=3}
      - name: Run tests
        run: pytest                    # Ejecutar pruebas:contentReference[oaicite:4]{index=4}
